### ISSUE TITLE
Embedded signing and also send the Envelope to signers email

### ISSUE THREAD

**Issue by jessiedeleon** [jondkinney/docusign_rest#114]
If I set **embedded: true** Embedded signing URL is successfully returned by DocuSign but there is NO email link sent to the Signers email.

**What should I do to do both? Embedded signing + send email link**

**Comment by pramodtech** [comment]
@jessiedeleon I don't think you can do that. Probably you can build send email feature in your app and send the link.

**Comment by jondkinney** [comment]
I think @pramodtech is correct here. The point of the embedded signing is to avoid generating an email from DocuSign so that you can control what that email looks and feels like. I'd recommend sending your own transactional email with a link to the page you have the embedded signing ceremony set up in.
